/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventasdao.ui.abm;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import ventasdao.controladores.CategoriaControlador;
import ventasdao.controladores.ICrud;
import ventasdao.objetos.Categoria;
import ventasdao.ui.grilla.GrillaCategoria;

/**
 *
 * @author Hugo Chanampe
 */
public class AbmCategoria extends javax.swing.JInternalFrame {

    /**
     * Creates new form AbmCategoria
     */
    private Categoria categoria;
    private ICrud<Categoria> categoriaControlador;
    private GrillaCategoria grillaCategoria;
    
    public AbmCategoria(ICrud<Categoria> categoriaControlador) {
        initComponents();
        
        this.categoriaControlador = categoriaControlador;
        ArrayList<Categoria> categorias = new ArrayList<>();

        try {
            categorias = (ArrayList<Categoria>) this.categoriaControlador.listar();
        } catch (Exception e) {
            Logger.getLogger(AbmCategoria.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(this, "Error al cargar las categorias", "Error", JOptionPane.ERROR_MESSAGE);
        }

        grillaCategoria = new GrillaCategoria(categorias);
        TablaDeCategorias.setModel(grillaCategoria);
    }
    
    
    private boolean validateFields(){
    
        if(jtfDenominacion.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "El campo denominacion no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        return true;
    }
    
    public void limpiarCampos(){
    
    jtfDenominacion.setText("");
    jtfDescripcion.setText("");
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfDenominacion = new javax.swing.JTextField();
        jtfDescripcion = new javax.swing.JTextField();
        agregarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDeCategorias = new javax.swing.JTable();
        modificarButton = new javax.swing.JButton();
        jtfId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        eliminarCategoriaButton = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setText("Denominacion");

        jLabel2.setText("Descripcion");

        jtfDenominacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDenominacionActionPerformed(evt);
            }
        });

        agregarButton.setText("Agregar");
        agregarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarButtonMouseClicked(evt);
            }
        });
        agregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarButtonActionPerformed(evt);
            }
        });

        TablaDeCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaDeCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDeCategoriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaDeCategorias);

        modificarButton.setText("Modificar");
        modificarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarButtonActionPerformed(evt);
            }
        });

        jtfId.setEnabled(false);
        jtfId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfIdActionPerformed(evt);
            }
        });

        jLabel3.setText("Id");

        eliminarCategoriaButton.setText("Eliminar");
        eliminarCategoriaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarCategoriaButtonMouseClicked(evt);
            }
        });
        eliminarCategoriaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarCategoriaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(agregarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modificarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtfDescripcion)
                    .addComponent(jtfDenominacion)
                    .addComponent(jtfId)
                    .addComponent(eliminarCategoriaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jtfDenominacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agregarButton)
                            .addComponent(modificarButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminarCategoriaButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarButtonActionPerformed

    

            if (validateFields()) {

                // TODO add your handling code here:

                categoria = new Categoria();

    

                categoria.setDenominacion(jtfDenominacion.getText());

                categoria.setDescripcion(jtfDescripcion.getText());

    

                try {

                    categoriaControlador.crear(categoria);

                } catch (Exception ex) {

                    Logger.getLogger(AbmCategoria.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "Error al crear la categoria", "Error", JOptionPane.ERROR_MESSAGE);

                }

    

                try {

                    grillaCategoria = new GrillaCategoria((ArrayList<Categoria>) categoriaControlador.listar());
                    TablaDeCategorias.setModel(grillaCategoria);

                } catch (Exception e) {

                    Logger.getLogger(AbmCategoria.class.getName()).log(Level.SEVERE, null, e);
                    JOptionPane.showMessageDialog(this, "Error al cargar las categorias", "Error", JOptionPane.ERROR_MESSAGE);

                }

            }

        }//GEN-LAST:event_agregarButtonActionPerformed

    private void agregarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarButtonMouseClicked

    }//GEN-LAST:event_agregarButtonMouseClicked

    private void TablaDeCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDeCategoriasMouseClicked
        
       this.categoria = grillaCategoria.getCategoriaFromRow(TablaDeCategorias.getSelectedRow());
       
       jtfDenominacion.setText(categoria.getDenominacion());
       jtfDescripcion.setText(categoria.getDescripcion());
       jtfId.setText( categoria.getId().toString() );
       
        System.out.println("Id: " + categoria.getId());
       
      
        
    }//GEN-LAST:event_TablaDeCategoriasMouseClicked

    private void modificarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarButtonActionPerformed
        if (validateFields()) {
            try {
                categoria = new Categoria();

                categoria.setDenominacion(jtfDenominacion.getText());
                categoria.setDescripcion(jtfDescripcion.getText());
                categoria.setId(Integer.parseInt(jtfId.getText()));

                categoriaControlador.modificar(categoria);
            } catch (Exception ex) {
                Logger.getLogger(AbmCategoria.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Error al modificar la categoria", "Error", JOptionPane.ERROR_MESSAGE);
            }

            try {
                grillaCategoria = new GrillaCategoria((ArrayList<Categoria>) categoriaControlador.listar());
                TablaDeCategorias.setModel(grillaCategoria);
            } catch (Exception ex) {
                Logger.getLogger(AbmCategoria.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Error al cargar las categorias", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_modificarButtonActionPerformed

    private void jtfIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfIdActionPerformed

    private void jtfDenominacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDenominacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDenominacionActionPerformed

    private void eliminarCategoriaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarCategoriaButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarCategoriaButtonMouseClicked

    private void eliminarCategoriaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarCategoriaButtonActionPerformed

        if (categoria != null) {
            int response = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que quieres eliminar esta categoría?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.YES_OPTION) {
                try {
                    categoriaControlador.eliminar(categoria);
                    limpiarCampos();
                    grillaCategoria = new GrillaCategoria((ArrayList<Categoria>) categoriaControlador.listar());
                    TablaDeCategorias.setModel(grillaCategoria);
                } catch (Exception ex) {
                    Logger.getLogger(AbmCategoria.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "Error al eliminar la categoria", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una categoría de la tabla", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_eliminarCategoriaButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaDeCategorias;
    private javax.swing.JButton agregarButton;
    private javax.swing.JButton eliminarCategoriaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtfDenominacion;
    private javax.swing.JTextField jtfDescripcion;
    private javax.swing.JTextField jtfId;
    private javax.swing.JButton modificarButton;
    // End of variables declaration//GEN-END:variables
}
