/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ventasdao.ui.abm;

import java.util.Date;
import ventasdao.controladores.ICrud;
import ventasdao.objetos.Factura;
import ventasdao.ui.grilla.FacturaGrilla;

/**
 *
 * @author patriciorios
 */
public class FacturaScreen extends javax.swing.JInternalFrame {

    /**
     * Creates new form FacturaScreen
     */
    private ICrud<Factura> facturaCrud;
    public FacturaScreen(ICrud<Factura> facturaCrud) {
        this.facturaCrud = facturaCrud;
        FacturaGrilla facturaGrilla = null;
        try {
            facturaGrilla = new FacturaGrilla(
                    this.facturaCrud.listar()
            );
        } catch (Exception ex) {
            System.getLogger(FacturaScreen.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        initComponents();
        this.jTable1.setModel(facturaGrilla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        CreateFacturaButton = new javax.swing.JButton();
        EditFacturaButton = new javax.swing.JButton();
        EliminarFacturaButton = new javax.swing.JButton();

        setClosable(true);
        setForeground(java.awt.Color.gray);
        setTitle("Factura");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "nombre", "cantidad", "precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        CreateFacturaButton.setText("Crear Factura");
        CreateFacturaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateFacturaButtonActionPerformed(evt);
            }
        });

        EditFacturaButton.setText("Editar Factura");
        EditFacturaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditFacturaButtonActionPerformed(evt);
            }
        });

        EliminarFacturaButton.setText("Eliminar Factura");
        EliminarFacturaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarFacturaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EliminarFacturaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditFacturaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CreateFacturaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CreateFacturaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EditFacturaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EliminarFacturaButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateFacturaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateFacturaButtonActionPerformed
        Factura emptyFactura = new Factura(
            null,
            new Date(),
            null,
                null
        );
        try{

            facturaCrud.crear(emptyFactura);
        } catch (Exception e){
            e.printStackTrace();
        }
        try {
            this.facturaCrud.listar().forEach(it -> {
                System.out.println(it);
            });
        } catch (Exception ex) {
            System.getLogger(FacturaScreen.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_CreateFacturaButtonActionPerformed

    private void EditFacturaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditFacturaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditFacturaButtonActionPerformed

    private void EliminarFacturaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarFacturaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarFacturaButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateFacturaButton;
    private javax.swing.JButton EditFacturaButton;
    private javax.swing.JButton EliminarFacturaButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
