/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ventasdao.ui.abm;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.TableColumnModel;
import ventasdao.controladores.ICrud;
import ventasdao.controladores.mocks.LineaFacturaControladorMock;
import ventasdao.objetos.Factura;
import ventasdao.objetos.LineaFactura;
import ventasdao.objetos.TipoDePagoDeFactura;
import ventasdao.ui.grilla.FacturaGrilla;
import ventasdao.ui.grilla.LineaGrilla;


/**
 *
 * @author patriciorios
 */
public class FacturaInternalLayaut extends javax.swing.JInternalFrame {
    private FacturaGrilla facturaGrilla;
    private DefaultComboBoxModel modelCombo;
    private ArrayList<TipoDePagoDeFactura> tiposDePago = new ArrayList<>();
    private ICrud<Factura> facturaCrud;
    private LineaFacturaControladorMock lineaFacturaICrud;
    private LineaGrilla lineaGrilla;
    public FacturaInternalLayaut(ICrud<Factura> facturaCrud,LineaFacturaControladorMock lineaFacturaCrud) {
        this.facturaCrud = facturaCrud;
        this.lineaFacturaICrud = lineaFacturaCrud;
        
        try {
            this.facturaGrilla = new FacturaGrilla(
                    this.facturaCrud.listar()
            );
        } catch (Exception ex) {
            System.getLogger(FacturaInternalLayaut.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        initComponents();
        this.FacturasTable.setModel(this.facturaGrilla);
        
        this.FacturasTable.getColumnModel().getColumn(0).setPreferredWidth(5);


        this.tiposDePago.add(TipoDePagoDeFactura.DEBITO);
        this.tiposDePago.add(TipoDePagoDeFactura.TARJETA);
        this.tiposDePago.add(TipoDePagoDeFactura.CONTADO);
        this.modelCombo = new DefaultComboBoxModel(this.tiposDePago.toArray());
        this.selectorDeTipoDePago.setModel(modelCombo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        FacturasTable = new javax.swing.JTable();
        CreateFacturaButton = new javax.swing.JButton();
        EditFacturaButton = new javax.swing.JButton();
        EliminarFacturaButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        selectorDeTipoDePago = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lineaTable = new javax.swing.JTable();

        setClosable(true);
        setForeground(java.awt.Color.gray);
        setTitle("Factura");

        FacturasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nombre", "cantidad", "precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        FacturasTable.getTableHeader().setReorderingAllowed(false);
        FacturasTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FacturasTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(FacturasTable);
        if (FacturasTable.getColumnModel().getColumnCount() > 0) {
            FacturasTable.getColumnModel().getColumn(0).setPreferredWidth(12);
        }

        CreateFacturaButton.setText("Crear Factura");
        CreateFacturaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateFacturaButtonActionPerformed(evt);
            }
        });

        EditFacturaButton.setText("Editar Factura");
        EditFacturaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditFacturaButtonActionPerformed(evt);
            }
        });

        EliminarFacturaButton.setText("Eliminar Factura");
        EliminarFacturaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarFacturaButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Selected id: ");

        selectorDeTipoDePago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectorDeTipoDePago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorDeTipoDePagoActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo de Pago");

        lineaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "id_producto", "producto", "precio", "cantidad", "total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lineaTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(lineaTable);
        if (lineaTable.getColumnModel().getColumnCount() > 0) {
            lineaTable.getColumnModel().getColumn(0).setResizable(false);
            lineaTable.getColumnModel().getColumn(0).setPreferredWidth(12);
            lineaTable.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EliminarFacturaButton)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(EditFacturaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(CreateFacturaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(selectorDeTipoDePago, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CreateFacturaButton)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EditFacturaButton)
                            .addComponent(selectorDeTipoDePago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EliminarFacturaButton)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(186, 186, 186))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateFacturaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateFacturaButtonActionPerformed
        Factura emptyFactura = new Factura(
            null,
            new Date(),
            null,
            (TipoDePagoDeFactura) this.selectorDeTipoDePago.getSelectedItem()
        );
        try{

            facturaCrud.crear(emptyFactura);
        } catch (Exception e){
            e.printStackTrace();
        }
        try {
            this.facturaGrilla = new FacturaGrilla(this.facturaCrud.listar());
            this.FacturasTable.setModel(this.facturaGrilla);
        } catch (Exception ex) {
            System.getLogger(FacturaInternalLayaut.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_CreateFacturaButtonActionPerformed

    private void EditFacturaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditFacturaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditFacturaButtonActionPerformed

    private void EliminarFacturaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarFacturaButtonActionPerformed
    }//GEN-LAST:event_EliminarFacturaButtonActionPerformed

    private void FacturasTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FacturasTableMouseClicked
        try {
            //TODO: aca es
            Integer selectedRow = this.FacturasTable.getSelectedRow();
            Factura factura = this.facturaGrilla.getFacturaByIndex(selectedRow);
            System.out.println(factura);
            
            this.lineaGrilla = new LineaGrilla(this.lineaFacturaICrud.listarPorFacturaId(factura.getId()));
            this.lineaTable.setModel(this.lineaGrilla);
        } catch (Exception ex) {
            System.getLogger(FacturaInternalLayaut.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_FacturasTableMouseClicked

    private void selectorDeTipoDePagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorDeTipoDePagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectorDeTipoDePagoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateFacturaButton;
    private javax.swing.JButton EditFacturaButton;
    private javax.swing.JButton EliminarFacturaButton;
    private javax.swing.JTable FacturasTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable lineaTable;
    private javax.swing.JComboBox<String> selectorDeTipoDePago;
    // End of variables declaration//GEN-END:variables
}
