/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ventasdao.ui.abm;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

import ventasdao.controladores.ICrud;
import ventasdao.controladores.mocks.LineaFacturaControladorMock;
import ventasdao.controladores.mocks.ProductoControladorMock;
import ventasdao.objetos.*;
import ventasdao.ui.grilla.FacturaGrilla;
import ventasdao.ui.grilla.LineaGrilla;
import ventasdao.ui.grilla.ProductoGrillaOnFacturaScreen;


/**
 *
 * @author patriciorios
 */
public class FacturaInternalLayaut extends javax.swing.JInternalFrame {
    private FacturaGrilla facturaGrilla;
    private DefaultComboBoxModel modelCombo;
    private DefaultComboBoxModel categoriaFilterComboBoxModel;
    private ArrayList<TipoDePagoDeFactura> tiposDePago = new ArrayList<>();
    private ICrud<Factura> facturaCrud;
    private LineaFacturaControladorMock lineaFacturaICrud;
    private LineaGrilla lineaGrilla;
    private Factura selectedFactura;
    private LineaFactura selectedLineaFactura;
    private ProductoControladorMock productoICrud;
    private ProductoGrillaOnFacturaScreen productoGrilla;

    private ICrud<Categoria> categoriaCrud;
    public FacturaInternalLayaut(
            ICrud<Factura> facturaCrud,
            LineaFacturaControladorMock lineaFacturaCrud,
            ProductoControladorMock productoICrud,
            ICrud<Categoria> categoriaCrud
            ) {
        this.facturaCrud = facturaCrud;
        this.lineaFacturaICrud = lineaFacturaCrud;
        this.productoICrud = productoICrud;
        this.categoriaCrud = categoriaCrud;
        
        try {
            this.facturaGrilla = new FacturaGrilla(
                    this.facturaCrud.listar()
            );
        } catch (Exception ex) {
            //System.getLogger(FacturaInternalLayaut.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        initComponents();
        this.FacturasTable.setModel(this.facturaGrilla);
        
        this.FacturasTable.getColumnModel().getColumn(0).setPreferredWidth(5);


        this.tiposDePago.add(TipoDePagoDeFactura.DEBITO);
        this.tiposDePago.add(TipoDePagoDeFactura.TARJETA);
        this.tiposDePago.add(TipoDePagoDeFactura.CONTADO);
        this.modelCombo = new DefaultComboBoxModel(this.tiposDePago.toArray());
        this.selectorDeTipoDePago.setModel(modelCombo);

        try {
            this.productoGrilla = new ProductoGrillaOnFacturaScreen(this.productoICrud.listar());
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        this.productoTable.setModel(this.productoGrilla);
        javax.swing.table.TableColumn column = this.productoTable.getColumnModel().getColumn(0);


        try {
            this.categoriaFilterComboBoxModel = new DefaultComboBoxModel(this.categoriaCrud.listar().toArray());
            this.categoriaFilterComboBox.setModel(this.categoriaFilterComboBoxModel);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        this.FacturasTable.getColumnModel().getColumn(0).setPreferredWidth(15);
        this.FacturasTable.getColumnModel().getColumn(0).setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        FacturasTable = new javax.swing.JTable();
        CreateFacturaButton = new javax.swing.JButton();
        updateFacturaButton = new javax.swing.JButton();
        eliminarFacturaButton = new javax.swing.JButton();
        selectedFacturaIdText = new javax.swing.JLabel();
        selectorDeTipoDePago = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lineaFacturaTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        productoTable = new javax.swing.JTable();
        productNameFilterTextField = new javax.swing.JTextField();
        categoriaFilterComboBox = new javax.swing.JComboBox<>();
        cantidadProductoSpinner = new javax.swing.JSpinner();
        productNameText = new javax.swing.JLabel();
        cantidadText = new javax.swing.JLabel();
        productPriceText = new javax.swing.JLabel();
        productIdText = new javax.swing.JLabel();
        lineaFacturaIdText = new javax.swing.JLabel();
        updateLineaButton = new javax.swing.JButton();
        deleteLineaButton = new javax.swing.JButton();
        cantidadText1 = new javax.swing.JLabel();
        cantidadText2 = new javax.swing.JLabel();
        cancelarEditButton = new javax.swing.JButton();

        setClosable(true);
        setForeground(java.awt.Color.gray);
        setTitle("Factura");

        FacturasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "fecha", "tipo pago", "total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        FacturasTable.getTableHeader().setReorderingAllowed(false);
        FacturasTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FacturasTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(FacturasTable);
        if (FacturasTable.getColumnModel().getColumnCount() > 0) {
            FacturasTable.getColumnModel().getColumn(0).setPreferredWidth(12);
        }

        CreateFacturaButton.setText("Crear Factura");
        CreateFacturaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateFacturaButtonActionPerformed(evt);
            }
        });

        updateFacturaButton.setText("Actualizar Factura");
        updateFacturaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateFacturaButtonActionPerformed(evt);
            }
        });

        eliminarFacturaButton.setText("Eliminar Factura");
        eliminarFacturaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarFacturaButtonActionPerformed(evt);
            }
        });

        selectedFacturaIdText.setText("Selected id: ");

        selectorDeTipoDePago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectorDeTipoDePago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorDeTipoDePagoActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo de Pago");

        lineaFacturaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "id_producto", "producto", "precio", "cantidad", "total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lineaFacturaTable.getTableHeader().setReorderingAllowed(false);
        lineaFacturaTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lineaFacturaTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lineaFacturaTable);
        if (lineaFacturaTable.getColumnModel().getColumnCount() > 0) {
            lineaFacturaTable.getColumnModel().getColumn(0).setResizable(false);
            lineaFacturaTable.getColumnModel().getColumn(0).setPreferredWidth(12);
            lineaFacturaTable.getColumnModel().getColumn(5).setResizable(false);
        }

        productoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "nombre", "precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        productoTable.getTableHeader().setReorderingAllowed(false);
        productoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productoTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(productoTable);
        if (productoTable.getColumnModel().getColumnCount() > 0) {
            productoTable.getColumnModel().getColumn(0).setPreferredWidth(3);
        }

        productNameFilterTextField.setToolTipText("Nombre de Producto");
        productNameFilterTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNameFilterTextFieldActionPerformed(evt);
            }
        });
        productNameFilterTextField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                productNameFilterTextFieldPropertyChange(evt);
            }
        });
        productNameFilterTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                productNameFilterTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                productNameFilterTextFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                productNameFilterTextFieldKeyTyped(evt);
            }
        });

        categoriaFilterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        categoriaFilterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaFilterComboBoxActionPerformed(evt);
            }
        });

        productNameText.setText("Producto:");

        cantidadText.setText("filtrar por nombre");

        productPriceText.setText("Precio:");

        productIdText.setText("Id:");

        lineaFacturaIdText.setText("linea id:");

        updateLineaButton.setText("Actualizar Linea");
        updateLineaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateLineaButtonActionPerformed(evt);
            }
        });

        deleteLineaButton.setText("Eliminar Linea");
        deleteLineaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteLineaButtonActionPerformed(evt);
            }
        });

        cantidadText1.setText("Cantidad");

        cantidadText2.setText("filtrar por categoria");

        cancelarEditButton.setText("Cancelar Edit");
        cancelarEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarEditButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(productNameFilterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cantidadText2)
                                    .addComponent(categoriaFilterComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cantidadProductoSpinner)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(productNameText)
                                    .addComponent(productPriceText)
                                    .addComponent(productIdText))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cantidadText)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lineaFacturaIdText)
                                .addGap(56, 56, 56)
                                .addComponent(updateLineaButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteLineaButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelarEditButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(30, 30, 30)
                                .addComponent(updateFacturaButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selectorDeTipoDePago, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selectedFacturaIdText)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eliminarFacturaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(CreateFacturaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 45, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(422, 422, 422)
                    .addComponent(cantidadText1)
                    .addContainerGap(450, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateFacturaButton)
                    .addComponent(jLabel2)
                    .addComponent(updateFacturaButton)
                    .addComponent(lineaFacturaIdText)
                    .addComponent(updateLineaButton)
                    .addComponent(deleteLineaButton)
                    .addComponent(cancelarEditButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selectorDeTipoDePago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eliminarFacturaButton)
                            .addComponent(selectedFacturaIdText))
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cantidadText)
                            .addComponent(cantidadText2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(productNameFilterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categoriaFilterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cantidadProductoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(productNameText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(productPriceText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(productIdText)))))
                .addGap(237, 237, 237))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(255, 255, 255)
                    .addComponent(cantidadText1)
                    .addContainerGap(517, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateFacturaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateFacturaButtonActionPerformed
        Factura emptyFactura = new Factura(
            null,
            new Date(),
            null,
            (TipoDePagoDeFactura) this.selectorDeTipoDePago.getSelectedItem()
        );
        try{

            facturaCrud.crear(emptyFactura);
        } catch (Exception e){
            e.printStackTrace();
        }
        try {
            this.facturaGrilla = new FacturaGrilla(this.facturaCrud.listar());
            this.FacturasTable.setModel(this.facturaGrilla);
        } catch (Exception ex) {
            //System.getLogger(FacturaInternalLayaut.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_CreateFacturaButtonActionPerformed

    private void updateFacturaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateFacturaButtonActionPerformed
        try {
            this.selectedFactura.setTypeOfPayment((TipoDePagoDeFactura) this.selectorDeTipoDePago.getSelectedItem());
            System.out.println("Updating factura: " + this.selectedFactura);
            this.facturaCrud.modificar(this.selectedFactura);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }

        try {
            this.facturaGrilla = new FacturaGrilla(this.facturaCrud.listar());
            this.FacturasTable.setModel(this.facturaGrilla);
            this.FacturasTable.getColumnModel().getColumn(0).setPreferredWidth(15);
            this.FacturasTable.getColumnModel().getColumn(0).setResizable(false);


        } catch (Exception ex) {
            //System.getLogger(FacturaInternalLayaut.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_updateFacturaButtonActionPerformed

    private void eliminarFacturaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarFacturaButtonActionPerformed
        if(this.selectedFactura != null){
            try {
                this.facturaCrud.eliminar(this.selectedFactura);
            } catch (Exception e) {
                throw new RuntimeException(e);
            }

            try {
                this.facturaGrilla = new FacturaGrilla(this.facturaCrud.listar());
                this.FacturasTable.setModel(this.facturaGrilla);
            } catch (Exception ex) {
            }
        }
    }//GEN-LAST:event_eliminarFacturaButtonActionPerformed


    private void FacturasTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FacturasTableMouseClicked
        try {
            System.out.println("Selected factura: " + this.selectedFactura);

            Integer selectedRow = this.FacturasTable.getSelectedRow();
            Factura factura = this.facturaGrilla.getFacturaByIndex(selectedRow);


            this.selectedFactura = factura;
            this.updateFacturaUIComponents();
            this.refreshLineaFacturaTable();

        } catch (Exception ex) {
            System.out.println("Error selecting factura: " + ex.getMessage());
            System.out.println("Error selecting factura: " + ex.toString());

            //System.getLogger(FacturaInternalLayaut.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_FacturasTableMouseClicked

    private void updateFacturaUIComponents(){
        if(this.selectedFactura == null){
            this.modelCombo.setSelectedItem(TipoDePagoDeFactura.CONTADO);
        }else{
            this.modelCombo.setSelectedItem(this.selectedFactura.getTypeOfPayment());
            this.selectedFacturaIdText.setText("Selected id: " + this.selectedFactura.getId());
        }

        refreshLineaFacturaTable();
    }
    private void selectorDeTipoDePagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorDeTipoDePagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectorDeTipoDePagoActionPerformed

    private void productNameFilterTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameFilterTextFieldActionPerformed
        System.out.println("Filtering products by name: " + this.productNameFilterTextField.getText());
    }//GEN-LAST:event_productNameFilterTextFieldActionPerformed

    private void lineaFacturaTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lineaFacturaTableMouseClicked
        Integer selectedRow = this.lineaFacturaTable.getSelectedRow();
        LineaFactura lineaFactura = this.lineaGrilla.getLineaFacturaByIndex(selectedRow);
        this.selectedLineaFactura = lineaFactura;

        refreshLineaFacturaUIComponents();

    }//GEN-LAST:event_lineaFacturaTableMouseClicked

    private void deleteLineaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteLineaButtonActionPerformed
        if(this.selectedLineaFactura != null && this.selectedLineaFactura.getId() != null){
            try {
                this.lineaFacturaICrud.eliminar(this.selectedLineaFactura);
                refreshLineaFacturaTable();
                clearLineaFacturaSelection();
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        }
    }//GEN-LAST:event_deleteLineaButtonActionPerformed

    private void updateLineaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateLineaButtonActionPerformed
        if(this.selectedLineaFactura != null){
            try {
                Integer nuevaCantidad = (Integer) this.cantidadProductoSpinner.getValue();
                this.selectedLineaFactura.setCantidad(nuevaCantidad);
                if(this.selectedLineaFactura.getId() == null){
                    System.out.println("La linea de factura es nueva, creando...");
                    this.lineaFacturaICrud.crear(this.selectedLineaFactura);
                }else{
                    System.out.println("La linea de factura ya existe, actualizando...");
                    this.lineaFacturaICrud.modificar(this.selectedLineaFactura);
                }
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
            refreshLineaFacturaTable();
        }
    }//GEN-LAST:event_updateLineaButtonActionPerformed

    private void productNameFilterTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productNameFilterTextFieldKeyTyped
        
    }//GEN-LAST:event_productNameFilterTextFieldKeyTyped

    private void productNameFilterTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productNameFilterTextFieldKeyPressed

    }//GEN-LAST:event_productNameFilterTextFieldKeyPressed

    private void productNameFilterTextFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_productNameFilterTextFieldPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_productNameFilterTextFieldPropertyChange

    private void productNameFilterTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productNameFilterTextFieldKeyReleased
        filterProducts();
    }//GEN-LAST:event_productNameFilterTextFieldKeyReleased

    private void productoTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productoTableMouseClicked
        if (this.selectedFactura == null) {
            System.out.println("Por favor, seleccione una factura primero.");
            return;
        }

        Integer selectedRow = this.productoTable.getSelectedRow();
        if (selectedRow < 0) {
            return; // No product selected
        }
        Producto producto = this.productoGrilla.getProductoByIndex(selectedRow);
        System.out.println("Producto seleccionado: " + producto);

        if (this.selectedLineaFactura == null) {
            // It's a new line
            this.selectedLineaFactura = new LineaFactura(
                null, // id
                1,    // cantidad
                producto,
                this.selectedFactura.getId()
            );
        } else {
            // A line is already selected, so update its product.
            this.selectedLineaFactura.setProducto(producto);
            // If it was the empty placeholder line, its quantity was 0. Let's set it to 1.
            if (this.selectedLineaFactura.getCantidad() == 0) {
                this.selectedLineaFactura.setCantidad(1);
            }
        }

        refreshLineaFacturaUIComponents();
    }//GEN-LAST:event_productoTableMouseClicked

    private void productCategoryFilterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        filterProducts();
    }

    private void filterProducts() {
        String nameFilter = productNameFilterTextField.getText();
        Object selectedCategoryObj = this.categoriaFilterComboBox.getSelectedItem();

        ventasdao.objetos.Categoria categoryFilter = null;
        if (selectedCategoryObj instanceof ventasdao.objetos.Categoria) {
            categoryFilter = (ventasdao.objetos.Categoria) selectedCategoryObj;
        }

        try {
            java.util.List<ventasdao.objetos.Producto> filteredProducts = productoICrud.filterByNameAndCategory(nameFilter, categoryFilter);
            productoGrilla = new ProductoGrillaOnFacturaScreen(filteredProducts);
            productoTable.setModel(productoGrilla);
        } catch (Exception e) {
            // Handle exception, maybe show a dialog
            e.printStackTrace();
        }
    }

    private void cancelarEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarEditButtonActionPerformed
        this.selectedFactura = null;
        this.FacturasTable.clearSelection();
        this.selectedFacturaIdText.setText("Selected id: ");

        clearLineaFacturaSelection();

        refreshLineaFacturaTable();
    }//GEN-LAST:event_cancelarEditButtonActionPerformed

    private void categoriaFilterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaFilterComboBoxActionPerformed
        System.out.println("Filtering products by category: " + this.categoriaFilterComboBox.getSelectedItem());

        if(this.productoICrud == null){
            System.out.println("Producto ICrud es null");
            return;
        }

        try {
            Categoria selectedCategoria = (Categoria) this.categoriaFilterComboBox.getSelectedItem();
            if(selectedCategoria == null){
                this.productoGrilla = new ProductoGrillaOnFacturaScreen(this.productoICrud.listar());
            } else {
                this.productoGrilla = new ProductoGrillaOnFacturaScreen(this.productoICrud.listarPorCategoria(selectedCategoria));
            }
            this.productoTable.setModel(this.productoGrilla);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }//GEN-LAST:event_categoriaFilterComboBoxActionPerformed

    private void clearLineaFacturaSelection() {
        this.selectedLineaFactura = null;
        this.lineaFacturaTable.clearSelection();
        this.lineaFacturaIdText.setText("Linea ID: ");
        this.productIdText.setText("Id: ");
        this.productNameText.setText("Producto: ");
        this.productPriceText.setText("Precio: ");
        this.cantidadProductoSpinner.setValue(0);
    }

    public void refreshLineaFacturaUIComponents(){
        System.out.println("Refreshing Linea Factura UI Components");
        if(this.selectedLineaFactura == null){
            // This case is handled by clearLineaFacturaSelection, but as a safeguard:
            clearLineaFacturaSelection();
            return;
        }

        System.out.println("Selected Linea Factura: " + this.selectedLineaFactura);
        this.lineaFacturaIdText.setText("Linea ID: " + this.selectedLineaFactura.getId());

        if (this.selectedLineaFactura.getProducto() != null) {
            this.productIdText.setText("Id: " + this.selectedLineaFactura.getProducto().getId());
            this.productNameText.setText("Producto: " + this.selectedLineaFactura.getProducto().getNombre());
            this.productPriceText.setText("Precio: " + this.selectedLineaFactura.getProducto().getPrecio() + " $");
        } else {
            this.productIdText.setText("Id: ");
            this.productNameText.setText("Producto: ");
            this.productPriceText.setText("Precio: ");
        }

        this.cantidadProductoSpinner.setValue(this.selectedLineaFactura.getCantidad());

        if (this.selectedFactura != null) {
            this.selectedFacturaIdText.setText("Selected id: " + this.selectedFactura.getId());
        }
    }
    public void refreshLineaFacturaTable(){
        List<LineaFactura> lineasDeFactura = new ArrayList<>();
        try {
            if (this.selectedFactura != null) {
                // Create a copy of the list to avoid modifying the original list from the mock controller
                lineasDeFactura = new ArrayList<>(this.lineaFacturaICrud.listarPorFacturaId(this.selectedFactura.getId()));

                if(lineasDeFactura.isEmpty() || lineasDeFactura.get(lineasDeFactura.size()-1).getId() != null){
                    lineasDeFactura.add(new LineaFactura(
                            null,
                            0,
                            new Producto(
                                    0,
                                    "",
                                    "",
                                    0.0f,
                                    null
                            ),
                            this.selectedFactura.getId()
                    ));
                }
                System.out.println("Lineas de Factura para la factura id " + this.selectedFactura.getId() + ": " + lineasDeFactura);
            }
        } catch (Exception e) {
            // It's better to show an error message to the user than to crash
            // For now, we'll keep the runtime exception as it was the previous behavior for errors.
            throw new RuntimeException(e);
        }
        this.lineaGrilla = new LineaGrilla(lineasDeFactura);
        this.lineaFacturaTable.setModel(this.lineaGrilla);
        lineaFacturaTable.getColumnModel().getColumn(0).setResizable(false);
        lineaFacturaTable.getColumnModel().getColumn(0).setPreferredWidth(15);
        lineaFacturaTable.getColumnModel().getColumn(5).setResizable(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateFacturaButton;
    private javax.swing.JTable FacturasTable;
    private javax.swing.JButton cancelarEditButton;
    private javax.swing.JSpinner cantidadProductoSpinner;
    private javax.swing.JLabel cantidadText;
    private javax.swing.JLabel cantidadText1;
    private javax.swing.JLabel cantidadText2;
    private javax.swing.JComboBox<String> categoriaFilterComboBox;
    private javax.swing.JButton deleteLineaButton;
    private javax.swing.JButton eliminarFacturaButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lineaFacturaIdText;
    private javax.swing.JTable lineaFacturaTable;
    private javax.swing.JLabel productIdText;
    private javax.swing.JTextField productNameFilterTextField;
    private javax.swing.JLabel productNameText;
    private javax.swing.JLabel productPriceText;
    private javax.swing.JTable productoTable;
    private javax.swing.JLabel selectedFacturaIdText;
    private javax.swing.JComboBox<String> selectorDeTipoDePago;
    private javax.swing.JButton updateFacturaButton;
    private javax.swing.JButton updateLineaButton;
    // End of variables declaration//GEN-END:variables
}
