/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventasdao.ui;

import java.awt.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import ventasdao.controladores.ICrud;
import ventasdao.controladores.mocks.CategoriaControladorMock;
import ventasdao.controladores.mocks.FacturaControladorMock;
import ventasdao.controladores.mocks.LineaFacturaControladorMock;
import ventasdao.controladores.mocks.ProductoControladorMock;
import ventasdao.objetos.Categoria;
import ventasdao.objetos.Factura;
import ventasdao.ui.abm.AbmCategoria;
import ventasdao.ui.abm.AbmCliente;
import ventasdao.ui.abm.AbmCliente;
import ventasdao.ui.abm.AbmProducto;
import ventasdao.ui.abm.FacturaInternalLayaut;

/**
 *
 * @author Hugo Chanampe
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    
    public enum Pantallas{
        PRODUCTO,
        FACTURAS,
        CLIENTE,
        TIPO_CLIENTE,
        CATEGORIA
    }
    
    private ICrud<Factura> facturaCrud;
    private LineaFacturaControladorMock lineaFacturaControlador;
    private ProductoControladorMock productoControladorMock;

    private ICrud<Categoria> categoriaCrud;
    public Principal() {
        this.lineaFacturaControlador = new LineaFacturaControladorMock();
        this.facturaCrud = new FacturaControladorMock();
        this.categoriaCrud = new CategoriaControladorMock();
        try {
            this.productoControladorMock = new ProductoControladorMock();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }

        initComponents();

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainContainer = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        NavCategoriasButton = new javax.swing.JButton();
        NavProductosButton = new javax.swing.JButton();
        NavClientesButton = new javax.swing.JButton();
        NavTipoClienteButon = new javax.swing.JButton();
        NavFacturas = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NavCategoriasButton.setText("Categorias");
        NavCategoriasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NavCategoriasButtonActionPerformed(evt);
            }
        });

        NavProductosButton.setText("Productos");
        NavProductosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NavProductosButtonActionPerformed(evt);
            }
        });

        NavClientesButton.setText("Clientes");
        NavClientesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NavClientesButtonActionPerformed(evt);
            }
        });

        NavTipoClienteButon.setText("Tipo Cliente");
        NavTipoClienteButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NavTipoClienteButonActionPerformed(evt);
            }
        });

        NavFacturas.setText("Facturas");
        NavFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NavFacturasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NavCategoriasButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NavProductosButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NavClientesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NavTipoClienteButon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NavFacturas)
                .addGap(0, 744, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NavProductosButton)
                    .addComponent(NavCategoriasButton)
                    .addComponent(NavClientesButton)
                    .addComponent(NavTipoClienteButon)
                    .addComponent(NavFacturas))
                .addContainerGap())
        );

        jPanel1.setLayout(new java.awt.CardLayout());

        MainContainer.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MainContainer.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout MainContainerLayout = new javax.swing.GroupLayout(MainContainer);
        MainContainer.setLayout(MainContainerLayout);
        MainContainerLayout.setHorizontalGroup(
            MainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MainContainerLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        MainContainerLayout.setVerticalGroup(
            MainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainContainerLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(625, 625, 625)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainContainer)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainContainer)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NavFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavFacturasActionPerformed
        FacturaInternalLayaut facturaScreen = new FacturaInternalLayaut(
                this.facturaCrud,
                this.lineaFacturaControlador,
                this.productoControladorMock,
                this.categoriaCrud
        );
        MainContainer.add(facturaScreen);
        facturaScreen.setPreferredSize(
                new Dimension(
                        this.MainContainer.getWidth(),
                        this.MainContainer.getHeight()-50
                )
        );
        facturaScreen.setLocation(
                (MainContainer.getWidth() - facturaScreen.getWidth()) / 2,50);
        facturaScreen.setVisible(true);


    }//GEN-LAST:event_NavFacturasActionPerformed

    private void NavTipoClienteButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavTipoClienteButonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NavTipoClienteButonActionPerformed

    private void NavClientesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavClientesButtonActionPerformed
        // TODO add your handling code here:
        AbmCliente abmCliente;
        try {
            abmCliente = new AbmCliente();
            MainContainer.add(abmCliente);
            abmCliente.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_NavClientesButtonActionPerformed

    private void NavProductosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavProductosButtonActionPerformed
        AbmProducto abmProducto = new AbmProducto();
        MainContainer.add(abmProducto);
        abmProducto.setVisible(true);
    }//GEN-LAST:event_NavProductosButtonActionPerformed

    private void NavCategoriasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavCategoriasButtonActionPerformed
        // TODO add your handling code here:
        AbmCategoria abmCategoria = new AbmCategoria();
        MainContainer.add(abmCategoria);
        abmCategoria.setVisible(true);
    }//GEN-LAST:event_NavCategoriasButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane MainContainer;
    private javax.swing.JButton NavCategoriasButton;
    private javax.swing.JButton NavClientesButton;
    private javax.swing.JButton NavFacturas;
    private javax.swing.JButton NavProductosButton;
    private javax.swing.JButton NavTipoClienteButon;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}